### ISSUE TITLE
Add process.exit(0) to response methods

### ISSUE THREAD

**Issue by Idered** [Syncano/syncano-server-js#64]
```js
if (!ARGS.token) {
  response.json({message: "invalid token"}, 400)
}

response.json({
  message: "we always will get this response because there is no process.exit"
})
```

**Comment by 23doors** [comment]
This is a bad idea. 
In new codebox (WIP) we use beforeExit https://nodejs.org/api/process.html#process_event_beforeexit to reuse docker container and process.exit() does not trigger it. process.exit should only be used when something went critically wrong, not as a part of standard behavior.

**Comment by 23doors** [comment]
As a workaround, you could automatically wrap user code in func() and then user could do something like:
```
if (!ARGS.token) {
  return response.json({message: "invalid token"}, 400)
}

response.json({
  message: "we always will get this response because there is no process.exit"
})
```

**Comment by 23doors** [comment]
Although, come to think of it, I'll probably try to handle process.exit() as well just in case

**Comment by Idered** [comment]
Thanks Robert for info. Let me know when you implement that handler. I'll wait until then.

I can send `process.exit('syncano-server-js')` which you could handle as normal script execution.

**Comment by 23doors** [comment]
ok, just confirmed and I'll be able to monkey patch process.exit() in user script context on my side (so that it propagates as an exception that is handled by the wrapper). So feel free to use it for response.json()
