### ISSUE TITLE
.with() doesn't work on relations 

### ISSUE THREAD

**Issue by mkucharz** [Syncano/syncano-server-js#69]
e.g.

```js
return data.socket
    .where('name', 'eq', socketName)
    .with('author')
    .with('keywords')
    .first()
```

Returns:

>                 {
>                   "links": {
>                     "self": "/v2/instances/socket-registry/classes/socket/objects/169/"
>                   },
>                   "updated_at": "2017-06-26T18:16:46.467052Z",
>                   "private": false,
>                   "owner_account": 29451,
>                   "keywords": [
>                     120,
>                     121,
>                     122,
>                     123
>                   ],
>                   "id": 169,
> ...

**Comment by Idered** [comment]
Does it work if you remove .with('autor') ?

**Comment by mkucharz** [comment]
My mistake... looks like everything works just fine!
